In [130]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [131]:
data=pd.read_csv('Crop_recommendation.csv',header=None)
data=data.drop(0)

In [132]:
data
type(data[5][4])


str

In [133]:
vectorizer = TfidfVectorizer()
vectorizer.fit(data[7])
print(vectorizer.vocabulary_)
vector = vectorizer.transform(data[7])
print(vector.shape)
print(type(vector))
print(vector.toarray())
for i in range(1,2201):
  data[7][i]=int(vectorizer.vocabulary_[data[7][i]])



{'rice': 20, 'maize': 11, 'chickpea': 3, 'kidneybeans': 9, 'pigeonpeas': 18, 'mothbeans': 13, 'mungbean': 14, 'blackgram': 2, 'lentil': 10, 'pomegranate': 19, 'banana': 1, 'mango': 12, 'grapes': 7, 'watermelon': 21, 'muskmelon': 15, 'apple': 0, 'orange': 16, 'papaya': 17, 'coconut': 4, 'cotton': 6, 'jute': 8, 'coffee': 5}
(2200, 22)
<class 'scipy.sparse._csr.csr_matrix'>
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [134]:
for i in range(8):
  data[i]=pd.to_numeric(data[i])

In [135]:
X=data.drop(columns=[7],axis=1);
Y=data[7]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=1)

In [136]:
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)
Y.describe()

count    2200.000000
mean       10.500000
std         6.345731
min         0.000000
25%         5.000000
50%        10.500000
75%        16.000000
max        21.000000
Name: 7, dtype: float64

In [145]:
model=svm.SVC(kernel='linear')
model.fit(X_train,Y_train)
X_train_prediction=model.predict(X_train)
training_data_acuracy=accuracy_score(X_train_prediction,Y_train)
print(training_data_acuracy)

0.9897727272727272


In [146]:
X_test_prediction=model.predict(X_test)
test_data_acuracy=accuracy_score(X_test_prediction,Y_test)
print(test_data_acuracy)

0.9931818181818182


In [142]:
input_data=(.01587,0.03003,0.006193,25.38,17.33,184.6,2019)
input_data_as_numpy=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)

[20]
